program: /Users/jakobtraeuble/PycharmProjects/DynLocRep_BrainAge/src/main_dyn_loc_rep.py
data_dir:
save_dir: /Users/jakobtraeuble/PycharmProjects/DynLocRep_BrainAge/output
save_model: 0
model: resnet18
pretrained: not
epochs: 50
batch_size: 32
lr: 1e-4
lr_decay: step
lr_decay_rate: 0.9
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 5e-5
method: expw
kernel: rbf
sigma: 2
tf: none
noise_std: 0.0
n_views: 2
modality: stiffness
wandb_name: NEW-baseline-
trial: 0
fold: 0
NN_nb_step_size: 0
end_NN_nb: 14
NN_nb_selection: 'manhattan'