program: /Users/jakobtraeuble/PycharmProjects/DynLocRep_BrainAge/src/pretrain_main_infonce.py
data_dir: /Users/jakobtraeuble/PycharmProjects/DynLocRep_BrainAge/src/data
save_dir: /Users/jakobtraeuble/PycharmProjects/DynLocRep_BrainAge/output
model: resnet18
epochs: 300
batch_size: 32
lr: 1e-4
lr_decay: step
lr_decay_rate: 0.9
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 5e-5
method: expw
kernel: rbf
sigma: 2
trial: 0
tf: none
wandb_name: 'github-test'
